[package]
name = "bn254"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
# ecAdd, ecMul, ecPairing
bn = { package = "substrate-bn", version = "0.6", default-features = false }
cty = "0.2.2"

[dev-dependencies]
hex = "0.4.3"
